version: '3'
services:
  on-doc-publisher:
    image: on-doc-publisher:latest
    ports:
      - "8080:8080"
    command: ["java","-jar","-Dspring.profiles.active=local", "/usr/src/on-doc-publisher-0.0.1-SNAPSHOT.jar"]
    restart: always
